# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88c42e120293daf1af3fa2ba2168ec515c5768d1cb5ce3bea4c0a1989f924b99c8f8311a1249a9af870045e93dbf21cf904daee0dfbc23e0b5f4e2ce2b77d52b

test:
  secret_key_base: 905a9b7c5696ac9a01b4965c3f84ee38946f2a52aad9bc31a6514174f143d711d42931aec115c01de3980412613bdfef241d5433eae946d8d52a308cb1f68181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
